from .seq_head import SeqHead
from .seq_head_concatattention import SEQHead_ConcatAttention
from .vgtr.vgtr import VGTRHead
from .detr_head.detr_head import DETRHead
from .deformable_detr_head.deformable_detr_head import DeformableDETRHead
from .deformable_detr_head.deformable_detr_head_debug import DeformableDETRHeadDebug
from .tgqs_detr_head.tgqs_detr_head import TextGuidedQuerySelectDETRHead
from .tgqs_kd_detr_head.tgqs_kd_detr_head import TextGuidedQuerySelectKDDETRHead